### ISSUE TITLE
Manque un README.md

### ISSUE THREAD

**Issue by epitre** [fduraffourg/usivry-me#1]
Salut Florian,

suite à un problème sur le site de l'USIvry Montagne Escalade, j'aimerai relivrer le site tout en gardant le contenu ^^
Serait-il possible d'avoir un README expliquant cette procédure au cas où il y ait quelque chose de particulier ?

PS : j'ai déjà les codes d'accès au FTP.

**Comment by fduraffourg** [comment]
Salut!

Le contenu de ce repo contient juste le squelette spip.
Les fichiers sont a mettre dans le dossier `squelettes` du serveur. Cf http://www.spip.net/fr_article3347.html

Tu peux faire la manip et ecrire le README, j'accepterai volontier ta pull request.

++
Florian

**Comment by epitre** [comment]
Très franchement, je n'ai pas envie de me former à SPIP.

Tant pis pour le README. Je vais me démerder autrement.


Carlos PEREIRA DE AMORIM

**Comment by fduraffourg** [comment]
C'est plus facile de demander aux autres de faire, que de faire soit meme, il n'y a pas de doute.

Il n'empeche que les infos dont tu as besoin sont dans ma premiere reponse :)

**Comment by epitre** [comment]
alors, je t'ai demandé d'écrire un README, pas de résoudre le problème de
sécurité que remonte google...

À moins que "[comme il] est plus facile de demander aux autres de faire,
que de faire soit meme", tu es envies de t'en occuper ????

Donc non, je ne te demande pas de faire des trucs oufs alors que je sais
pertinemment que tu n'es plus en région parisienne.

Juste de m'aider à avoir les bases pour te remplacer dans cette passe
difficile pour le site de la section.

Mais si tu considères que j'en demande trop. Trés bien, c'est noté! Inutile
de m'accuser de déléguer le travail aux autres en ne voulant rien faire
moi-même...


Carlos PEREIRA DE AMORIM

2017-03-10 15:03 GMT+01:00 Florian Duraffourg <notifications@github.com>:

**Comment by fduraffourg** [comment]
Et sinon par rapport aux informations du premier commentaire, il te manque qqch?

**Comment by epitre** [comment]
Le seul moyen pour moi de vérifier s'il me manque quelque chose serait de
faire la manip en risquant de casser le site.

Donc, tant que je pourrai éviter ce risque, je ferai autrement.

Et puis, quand je ne pourrai pas faire autrement, je ferai sans toi si j'ai
bien compris.

En tout cas, merci pour le lien, c'est mieux que rien.


Carlos PEREIRA DE AMORIM

**Comment by fduraffourg** [comment]
Tu dois te meprendre sur l'utilite de ce repos.

Il ne contient QUE le squelette du site. Et pour installer le squelette il suffit de copier les fichiers de ce repos dans le dossier `squelettes`. Je ne vois pas vraiment ce qu'il y a a mettre de plus dans le README.

Neanmoins j'ai l'impression que tu attends de moi une procedure pour faire la re-installation complete du site. Si c'est le cas j'ai du mal a comprendre le benefice de passer du temps a ecrire une telle procedure alors qu'il en existe tout un tas deja disponible sur internet. Il n'y a rien de particulier sur ce site. Les donnees sont en DB, le squelette dans ce repos et c'est une installation classique de Spip.

Si tu as des questions specifiques je peux y repondre, mais n'attends pas de moi que je re-ecrive ce qui est deja tres largement disponible sur internet.
